[package]
name = "RustyHack"
version = "1.0.0"
authors = ["Adollo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[profile.release]
lto = "fat"
codegen-units = 1
panic = 'abort'
